"use client";
import Link from "next/link";
import { FormEvent,useRef,useState } from "react";

type Finding={severity:string;title:string;explanation:string;file_path:string;line_hint:string;verification:string;citations:{url:string;label:string}[]};
type Report={pull_request_summary:string;verdict:string;findings:Finding[];positive_notes:string[];missing_context:string[];reviewed_files:string[];confidence:{level:string;reason:string}};
type Review={id:string;status:string;steps:{key:string;label:string;status:string;summary?:string}[];tool_calls:{tool_name:string;duration_ms:number}[];report?:Report;approved_report?:Report;error?:string;token_usage:number};
const API_URL=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
const LIVE_REPO=process.env.NEXT_PUBLIC_LIVE_DEMO_REPOSITORY||"c-y-s-s/frontend-agent-demo-shop";

export default function CodeReviewPage(){
 const [repository,setRepository]=useState("demo/frontend-agent-demo-shop"),[pr,setPr]=useState("3"),[mode,setMode]=useState<"replay"|"live">("replay"),[review,setReview]=useState<Review|null>(null),[loading,setLoading]=useState(false),[notice,setNotice]=useState(""); const source=useRef<EventSource|null>(null);
 function changeMode(next:"replay"|"live"){setMode(next);if(next==="live"&&repository==="demo/frontend-agent-demo-shop")setRepository(LIVE_REPO);if(next==="replay"&&repository===LIVE_REPO)setRepository("demo/frontend-agent-demo-shop");}
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setNotice("");setReview(null);source.current?.close();try{const response=await fetch(`${API_URL}/api/v1/code-reviews`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({repository,pull_request_number:Number(pr),mode,locale:"zh-TW"})});const body=await response.json();if(!response.ok)throw new Error(body.detail||"無法開始 Review");setReview(body);const events=new EventSource(`${API_URL}/api/v1/code-reviews/${body.id}/events`);source.current=events;events.addEventListener("review",m=>{const next=JSON.parse((m as MessageEvent).data);setReview(next);if(["waiting_approval","approved","rejected","failed"].includes(next.status))setLoading(false)});events.addEventListener("done",()=>{events.close();setLoading(false)});events.onerror=()=>{events.close();setLoading(false)}}catch(error){setLoading(false);setNotice(error instanceof Error?error.message:"Request failed")}}
 async function approve(){if(!review)return;const response=await fetch(`${API_URL}/api/v1/code-reviews/${review.id}/approve`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actor:"portfolio-reviewer"})});const body=await response.json();if(response.ok)setReview(body)}
 const report=review?.approved_report||review?.report;
 return <main><header className="topbar"><Link className="brand" href="/code-review"><span className="brand-mark">✓</span><span>Code Review Agent</span></Link><nav className="topbar-actions"><Link className="module-link" href="/">Task</Link><Link className="module-link" href="/api-analyzer">API</Link><Link className="module-link" href="/bug-investigator">Bug</Link></nav></header>
 <section className="workspace review-workspace"><div className="workspace-heading"><div><span>PR REVIEW · READ ONLY</span><h1>先看風險，再決定是否合併</h1><p>讀取受限 PR diff，只回報有證據、可驗證的問題，不評論個人風格。</p></div></div><form className="review-form" onSubmit={submit}><label><span>Repository</span><input value={repository} onChange={e=>setRepository(e.target.value)}/></label><label><span>Pull Request</span><input type="number" min="1" value={pr} onChange={e=>setPr(e.target.value)}/></label><div className="mode-picker"><button type="button" className={mode==="replay"?"selected":""} onClick={()=>changeMode("replay")}>Replay</button><button type="button" className={mode==="live"?"selected":""} onClick={()=>changeMode("live")}>Live AI</button></div><button className="run-button" disabled={loading}>{loading?"Review 中…":"開始 Review"}</button></form>{notice&&<div className="notice">{notice}</div>}</section>
 {review&&<section className="review-results"><div className="bug-result-status"><span>{review.status.replaceAll("_"," ")}</span><span>{review.token_usage} tokens</span></div>{review.error&&<div className="error-card"><p>{review.error}</p></div>}{!report&&!review.error&&<div className="analysis-loader"><span/><h3>正在讀取 PR diff</h3></div>}{report&&<><div className="review-verdict"><span>VERDICT</span><strong>{report.verdict.replaceAll("_"," ")}</strong><p>{report.pull_request_summary}</p><small>{report.confidence.level} confidence · {report.confidence.reason}</small></div><div className="review-findings">{report.findings.map((f,i)=><article key={`${f.file_path}-${i}`} className={`review-${f.severity}`}><header><span>{f.severity}</span><code>{f.file_path}</code></header><h2>{f.title}</h2><p>{f.explanation}</p><div><b>如何驗證</b><p>{f.verification}</p></div>{f.citations.map(c=><a key={c.url} href={c.url} target="_blank" rel="noreferrer">{c.label} ↗</a>)}</article>)}</div><details className="bug-detail-panel"><summary>查看 Review 範圍與 Agent 軌跡</summary><div className="review-context"><p>Reviewed: {report.reviewed_files.join(" · ")}</p><p>Missing context: {report.missing_context.join(" · ")||"—"}</p>{review.steps.map(s=><p key={s.key}>• {s.label} — {s.summary||s.status}</p>)}</div></details></>}{report&&review.status==="waiting_approval"&&<div className="approval-bar bug-simple-approval"><div><span>HUMAN CHECKPOINT</span><strong>只保存 Review 結果，不會寫回 GitHub。</strong></div><button className="approve-button" onClick={approve}>接受 Review 結果</button></div>}</section>}</main>}
